### ISSUE TITLE
Test issue 2

### ISSUE THREAD

**Issue by SgbVGvQz-2** [SgbVGvQz-1/DemoProject#2]
This is a test activity.

**Comment by SgbVGvQz-2** [comment]
Any updates?

**Comment by SgbVGvQz-1** [comment]
Is this same as Issue #1?
@SgbVGvQz-2

**Comment by SgbVGvQz-2** [comment]
> 
> 
> Is this same as Issue #1?
> @SgbVGvQz-2

I don't think so @SgbVGvQz-1.

**Comment by SgbVGvQz-2** [comment]
Ok, issue fixed now.

**Comment by SgbVGvQz-2** [comment]
This is not fixed completely. 
Reopening it.

**Comment by SgbVGvQz-2** [comment]
Now fixed!

**Comment by SgbVGvQz-1** [comment]
Thanks for the fix.
