### ISSUE TITLE
Test issue 3

### ISSUE THREAD

**Issue by SgbVGvQz-1** [SgbVGvQz-1/DemoProject#3]
This is a test bug.

**Comment by SgbVGvQz-2** [comment]
Also occurs for me.

**Comment by SgbVGvQz-2** [comment]
New comment posted after deleting previous comment - update 1
More lines added to text - update 2

**Comment by SgbVGvQz-1** [comment]
Can @SgbVGvQz-2 fix this bug?

**Comment by SgbVGvQz-2** [comment]
Actually, I cannot as I am not a contributor in the repository.

**Comment by SgbVGvQz-1** [comment]
Right, I will fix it.

**Comment by SgbVGvQz-1** [comment]
Fixed now!

**Comment by SgbVGvQz-2** [comment]
Cool!

**Comment by SgbVGvQz-2** [comment]
Cool
